---
title: "DCA Recon survey data PENIP"
author: "R. Cunning"
date: "2025-04-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
# Read in coral count data
dca0 <- readxl::read_xlsx("data/Compiled_DCA_RECON_Belt_data.xlsx") %>%
  janitor::clean_names()

dca <- dca0 %>%
  select(1:18) %>%
  rename(site = site_name)

# Read in site coordinates
dca_sites0 <- readxl::read_xlsx("data/Recon_Site_Coordinates_Extracted.xlsx") %>%
  janitor::clean_names()

dca_sites <- dca_sites0 %>%
  rename(site = transect) %>%
  group_by(site) %>%
  summarize(latitude = mean(as.numeric(latitude)), 
            longitude = mean(as.numeric(longitude)))

# Join
dca <- left_join(dca, dca_sites) %>%
  select(site, latitude, longitude, everything())
```


```{r}
# DCA taxonomy
dca <- dca %>%
  rename(taxon = coral_species) %>%
  mutate(taxon = case_when(taxon %in% c("PPOR", "PFUR", "PDIV") ~ "PBRA",
                           taxon %in% c("OFAV", "OANN", "OFRA", "OFAV\\") ~ "ORBI",
                           taxon %in% c("CNAT", "DLAB", "PSTR", "PCLI") ~ "FAVI",
                           taxon %in% c("AFRA", "AAGA", "AHUM", "ALAM", "AGA SP") ~ "AGAR",
                           taxon %in% c("MAD SP", "MADR", "MADSP", "MPHA") ~ "MADR",
                           taxon %in% c("MAUR", "MDEC") ~ "MADR",
                           taxon %in% c("SHYA", "SBOU") ~ "SOLE",
                           taxon %in% c("Scolymia Spp", "SCUB") ~ "SCOL",
                           taxon %in% c("SSID", "SRAD", "SIDSP", "Sid SP", "SID SP.", "SID SP") ~ "SIDE",
                           taxon %in% c("MYCSP", "Mycetophyllia spp.", "MLAM", "MALI") ~ "MYCE",
                           TRUE ~ taxon)) %>%
  filter(!taxon %in% c("CORAL", "Cup Coral"))

# Lump juveniles to family following DRM methods
dca <- dca %>%
  mutate(taxon = case_when(
    max_size_cm <= 4 & taxon %in% c("ISIN", "ISOP", "MANG", "MYCE", "SCOL") ~ "MUSS",
    max_size_cm <= 4 & taxon %in% c("FAVI", "FFRA", "MARE") ~ "FAVI",
    max_size_cm <= 4 & taxon %in% c("MMEA", "MEAN", "DCYL", "DSTO", "EFAS") ~ "MEAN",
    TRUE ~ taxon
  )) %>%
  droplevels()

tax <- dca %>% count(taxon)

# Convert DCA to counts (include zeros)
dca_counts <- dca %>%
  mutate(class = ifelse(max_size_cm >= 4, ">4cm", "<4cm")) %>%
  count(site, taxon, class) %>%
  complete(site, taxon, class = c(">4cm", "<4cm"), fill = list(n = 0)) %>%
  left_join(dca_sites, by = "site") %>%
  relocate(latitude, longitude, .after = site)
```

# Shedd surveys
```{r}
shedd <- read_csv("counts_long_full.csv") %>%
  mutate(site = as.character(site))

shedd <- shedd %>%
  mutate(taxon = case_when(taxon %in% c("PPOR", "PFUR", "PDIV") ~ "PBRA",
                           taxon %in% c("OFAV", "OANN", "OFRA", "OFAV\\") ~ "ORBI",
                           taxon %in% c("CNAT", "DLAB", "PSTR", "PCLI") ~ "FAVI",
                           taxon %in% c("AFRA", "AAGA", "AHUM", "ALAM", "AGA SP") ~ "AGAR",
                           taxon %in% c("MAD SP", "MADR", "MADSP", "MPHA") ~ "MADR",
                           taxon %in% c("MAUR", "MDEC") ~ "MADR",
                           taxon %in% c("SHYA", "SBOU") ~ "SOLE",
                           taxon %in% c("Scolymia Spp", "SCUB") ~ "SCOL",
                           taxon %in% c("SSID", "SRAD", "SIDSP", "Sid SP", "SID SP.", "SID SP") ~ "SIDE",
                           taxon %in% c("MYCSP", "Mycetophyllia spp.", "MLAM", "MALI") ~ "MYCE",
                           TRUE ~ taxon)) %>%
  droplevels()
```



```{r}
# Find area where both DCA and Shedd team surveyed
shedd_sites <- shedd %>%
  distinct(site, latitude, longitude)

all_sites <- bind_rows(dca = dca_sites, shedd = shedd_sites, .id = "dataset")

ggplot(all_sites, aes(x = longitude, y = latitude, color = dataset)) + 
  geom_point(alpha = 0.5)

overlap <- all_sites %>%
  filter(latitude > 26.080, 
         latitude < 26.105,
         longitude < -80.09)

ggplot(overlap, aes(x = longitude, y = latitude, color = dataset)) + 
  geom_point(alpha = 0.5)
```

```{r}
# Combine DCA and Shedd data and filter to just overlapping area
df <- bind_rows(
  dca = select(dca_counts, site, latitude, longitude, taxon, class, count = n),
  shedd = select(shedd, site, latitude, longitude, taxon, class, count),
  .id = "dataset"
) 

# Filter to just sites in overlapping area 
dff <- df %>%
  filter(site %in% unique(overlap$site))

# Remove any species unobserved in overlapping area
dff_counts <- dff %>% group_by(taxon) %>% summarize(total = sum(count)) %>% arrange(total)
absent_spp <- dff_counts %>% filter(total == 0) %>% pull(taxon)
dff <- dff %>%
  filter(!taxon %in% absent_spp)

# Add zeros for any species observed only in one dataset or the other
dff_completed <- dff %>%
  complete(nesting(dataset, site, latitude, longitude),
           taxon, class,
           fill = list(count = 0))
  


summ <- dff %>%
  group_by(dataset, taxon) %>%
  summarize(total = sum(count), .groups = "drop") %>%
  group_by(dataset) %>%
  mutate(pct = total / sum(total)) %>%
  ungroup() %>%
  pivot_wider(names_from = dataset, values_from = c(total, pct))

# Fix FFRA, MEAN, MUSS from Shedd

```

